### ISSUE TITLE
vunit overwrites default generics

### ISSUE THREAD

**Issue by nussbrot** [LarsAsplund/vunit#71] opened 2015-09-04 14:51 UTC
Hi,

i recently found a bug in vunit. It occurs when the testbench has a generic that you set via python script. The testbench instanciates an entity that has a generic of the same name, but uses the default value for that entity.
This default value then gets overwritten. I don't know if that description is very useful to the reader so i provide you with a test case. For me the expected behavior for this test is a pass, but it fails on my machine.

Best, Ralf.

**run.py**
```python
from os.path import join, dirname
from vunit import VUnit

root = dirname(__file__)

ui = VUnit.from_argv()
lib = ui.add_library("lib")
lib.add_source_files(join(root, "*.vhd"))

tb = lib.entity("tb_generic_bug")
tb.add_config(name="bug", generics=dict(g_val=False));
ui.main()
```
**bool_driver.vhd**
```vhdl
entity bool_driver is
  generic (
    g_val : boolean := true);
  port (
    outp  : out boolean);
end entity;

architecture rtl of bool_driver is
begin
  outp <= g_val;
end architecture;
```
**tb_generic_bug.vhd**
```vhd
entity tb_generic_bug is
  generic (
    runner_cfg : runner_cfg_t;
    g_val : boolean);
end entity;

architecture tb of tb_generic_bug is
  signal s_outp : boolean;
begin
  main : process
  begin
    test_runner_setup(runner, runner_cfg);
    assert(s_outp);
    test_runner_cleanup(runner);
  end process;

  dut : ENTITY lib.bool_driver
    port map ( outp => s_outp );
end architecture;
```

**Comment by LarsAsplund** [comment] 2015-09-04 15:38
@nussbrot  Yes, I see the same problem when running under ModelSim ALTERA STARTER EDITION 10.1d. What are you using? But I also get the problem when running from ModelSim itself without using VUnit so it seems like a bug.

**Comment by nussbrot** [comment] 2015-09-04 15:50
@LarsAsplund Oh so maybe it is a ModelSim bug? I have no access at the weekend so i will get back to you on monday, but it should be ModelSim 10.4. I will definitely run that test again without vunit.

**Comment by LarsAsplund** [comment] 2015-09-04 15:55
@nussbrot I had a look at the reference manual for the -g option we use when calling vsim. It says

_-g <Name>=<Value> …
(optional) Assigns a value to all specified VHDL generics and Verilog parameters that have
not received explicit values in generic maps, instantiations, or via defparams (such as toplevel
generics/parameters and generics/parameters that would otherwise receive their
default values)._

Is that _all_ different generics I've specified or also _all_ occurrences it can find at any hierarchical level?

**Comment by LarsAsplund** [comment] 2015-09-04 16:17
@nussbrot It seems to go even further. I made a test where I add another generic `g_val2` to the top-level testbench but not to `bool_driver`. I then created a new entity with the `g_val2` generic and set its default to `true`. This new entity was then instantiated in `bool_driver` without changing its default value for  `g_val2`. The generic set at the top-level with the `-g` option still found its way down the hierarchies to change the value for the new entity. I will do a quick google to see if this behaviour has been discussed elsewhere.

**Comment by joshrsmith** [comment] 2015-09-04 16:55
Is there a -G option instead?? I seem to remember a couple different options with the riviera simulator. It might have slightly different behavior. 

Josh

**Comment by LarsAsplund** [comment] 2015-09-04 17:05
Yes, there is a -G but

_-G<Name>=<Value> …
(optional) Same as -g (see above) except that it will also override generics/parameters that
received explicit values in generic maps, instantiations, or from defparams._

It seems to be applied globally as well. @joshrsmith Do you know how Riviera behaves?

**Comment by kraigher** [comment] 2015-09-05 11:08
How very unexpected and undesirable behavior. Thankfully the reference manual mentions that a hierarchical reference could be used to pinpoint a specific generic such as -g/top/foo=bar instead of -gfoo=bar. Thus it could be resolved and I have pushed a fix.

**Closed by kraigher** 2015-09-05 11:08 UTC

**Comment by kraigher** [comment] 2015-09-05 11:15
The fix is part of v0.29.0 release. The problem affected only Modelsim and not GHDL.
GHDL has got the `-g` flag because we suggested it to them when adding support for GHDL to VUnit so it did not have the unexpected behavior.

**Comment by nussbrot** [comment] 2015-09-07 09:30
Indeed strange behavior of ModelSim. I never expected that. Thank you for the quick fix!
